name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/release.keystore

      - name: Create local.properties
        run: |
          # Use "release.keystore" because Gradle interprets paths relative to the 'app' module
          echo "MY_RELEASE_KEYSTORE=release.keystore" > local.properties
          echo "MY_KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "MY_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "MY_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleFRRelease assembleESRelease

      # NEW STEP: Clean up secrets immediately
      - name: Clean up secrets
        if: always() # Run even if previous steps fail, so secrets are still cleaned
        run: |
          rm local.properties
          rm app/release.keystore

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/*/release/m444_fuel*-release.apk
          # app/build/outputs/apk/fr/release/m444_fuelFR-release.apk
          # app/build/outputs/apk/es/release/m444_fuelES-release.apk
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
